name: Run Colab Every 3 Days

on:
  schedule:
    - cron: "0 0 */3 * *"  # Runs every 3 days at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_colab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Google Colab Notebook
        uses: educational-websites/colab-batch@v1
        with:
          notebook: "ColabEventScrapper.ipynb" 
          parameters: |
            RECIPIENT_EMAIL=${{ secrets.RECIPIENT_EMAIL }}
            SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}
            SENDER_PASSWORD=${{ secrets.SMTP_SERVER }}
