name: Run Python Script Every 3 Days-v2

on:
  schedule:
    - cron: "0 0 */3 * *"  # Runs every 3 days at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Script
        run: python runer.py
